// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntpnzrqxufcwufgsaqom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cG56cnF4dWZjd3VmZ3NhcW9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODUzNDIsImV4cCI6MjA3MjU2MTM0Mn0.cDoV1JsNwzkaSmDSjBDQQWjRRragwQZFt737FSr6bC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});